<<<<<<< HEAD
export const SET_ALL_DRIVERS = "SET_ALL_DRIVERS"
export const SET_DRIVERS_FILTER = "SET_DRIVERS_FILTER";
export const SET_DRIVERS_ORDER = "SET_DRIVERS_ORDER" ;
export const SET_SELECTED_SOURCE = "SET_SELECTED_SOURCE" ;
=======
export const SEARCH_DRIVERS = 'SEARCH_DRIVERS';
export const FILTER_TEAMS = 'FILTER_TEAMS';
export const ORDER_DIVERS = 'ORDER_DIVERS';
>>>>>>> c7d2fb7363d3a74735678d63654ad9fee2249b78
