export const SET_ALL_DRIVERS = "SET_ALL_DRIVERS"
export const SET_DRIVERS_FILTER = "SET_DRIVERS_FILTER";
export const SET_DRIVERS_ORDER = "SET_DRIVERS_ORDER" ;
export const SET_SELECTED_SOURCE = "SET_SELECTED_SOURCE" ;
export const SET_DRIVERS_BY_NAME = "SET_DRIVERS_BY_NAME";

